### PR TITLE
Separate opam packages for lwt and async

### PR DESCRIPTION
**Pull request by bradlangel**
Based off of #3. Separates packages for lwt and async, so as to avoid depending on both. This follows the first four bullet points @mfp [outlined here](https://github.com/mfp/ocaml-statsd-client/pull/3#issuecomment-366538678). 
* Exposes three packages: `statsd-client`(with a deprecation warning for `Statsd_client.Lwt`), `statsd-client-lwt` and `statsd-client-async`.
* Packages can be installed locally by following these [opam instructions](https://opam.ocaml.org/doc/Packaging.html). 
* Gets rid of the compiler version dependency introduced in #3 for `statsd-client` and `statsd-client-lwt` but the dependency is kept for `statsd-client-async` since Async V0.10.0 depends on 4.0.1

### CODE REVIEW

**Comment by mfp** [comment]
I've glanced over the code + packaging changes and this looks great: the situation wrt. backwards compatibility is also about ideal; I will be referring to this when I try to learn jbuilder/dune once and for all in the future :) It's really nice that you managed to drop the version constraint for the separate base and lwt packages.

As for the ocaml version constraint, I got this idea to work with both async v0.9.0 and v0.10.0:

```ocaml
    open Core
    module Std = struct end
    open Async
    open Std
```

I see there may or may not be a `Core.Std` module inherited from `Core_kernel` -- it's not clear to me from the [docs](https://ocaml.janestreet.com/ocaml-core/latest/doc/core_kernel/Core_kernel/index.html). If it does exist, and is actually needed in `Statsd_client_async` (although I don't spot any obvious uses), we can drop the dummy `Std` module definition. 

I feel a bit uneasy about the config being implicitly shared between `Statsd_client_sync`, `Statsd_client_lwt` and `Statsd_client_async` via the global vars in `Statsd_client_core`, but (1) this gives the right semantics in `Statsd_client` and (2) it is hard to picture anybody relying on this to e.g. set the IP address and port in `Statsd_client_lwt`, yet use `Statsd_client_async` or vice-versa, so there should be no issue in the future when the (clearly global in scope) config from `Statsd_client` is dropped and the configs for the subpackages become distinct. So I believe the Config issue doesn't require further consideration for now beyond maybe documenting that the config in the `_sync`, `_lwt` and `_async` modules is shared atm. but might no longer be in the future to prevent the sort of shooting in the foot described above.

**Comment by bradlangel** [comment]
Wrt async, I'm hesitant to add this hack as it is confusing and seems likely to
contain bugs. I'm not sure that the effort to support older versions of ocaml
for async are worth the effort especially given that this statsd client up until
these pull requests has never supported async. I'd like to start the support
cycle of async with v0.10.0 and we can then support new versions of OCaml moving
forward with new version releases of the statsd-client-async package.

>(2) it is hard to picture anybody relying on this to e.g. set the IP address
> and port in Statsd_client_lwt, yet use Statsd_client_async or vice-versa, so

Fyi, in this pull request, I removed async support in statsd-client since we'd
like to get rid of statsd-client in favor of _sync, _lwt & _async
flavors. Opting instead to only have a backwards compatible statsd-client
package using the other packages. Regardless, your example is definitely correct
and I agree with everything you said.

> there should be no issue in the future when the (clearly global in scope)
> config from Statsd_client is dropped and the configs for the subpackages become
> distinct.

Totally agree.

>for now beyond maybe documenting that the config in the _sync, _lwt and _async
> modules is shared atm. but might no longer be in the future to prevent the sort
> of shooting in the foot described above.

Agreed. I can add this documentation later today or tomorrow.


The roadmap that I'd like to see for this repository moving forward is as
follows:

[] merge pull request #2, #3, and #4 after I add some documentation about the
   shared packages ;)
[] merge pull request 3(expose statsd format and send functions) and 4(statsd
   extended: dogstatsd support) that I did to my fork here:
   https://github.com/arenadotio/ocaml-statsd-client/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed
[] Add testing which I'm working on for my fork and I'll upstream it when the
   above bullet points get merged.
   * cleanup the directories to have lib and test directories

[] Add CircleCI support so our tests get ran on each pull request
[] Clean up readme, documentation, etc.
[] Publish new packages(lwt & async) along with deprecated package
[] Pull request to deprecate statsd-client

   * clean up the global config
   * clean up global logging to use lwt logging and async logging where appropriate

[] Publish updated packages

All of the above, I'm more than happy to do over the next week or two. I just
want to be on the same page as you. Let me know what you think!

**Comment by mfp** [comment]
On Fri, Mar 30, 2018 at 12:50:05PM -0700, Brad Langel wrote:
> Wrt async, I'm hesitant to add this hack as it is confusing and seems likely to
> contain bugs. I'm not sure that the effort to support older versions of ocaml
> for async are worth the effort especially given that this statsd client up until
> these pull requests has never supported async. I'd like to start the support
> cycle of async with v0.10.0 and we can then support new versions of OCaml moving
> forward with new version releases of the statsd-client-async package.

OK, no compatibility broken and I guess people in the Core/Async ecosystem
stay usually up-to-date.

> 
> Agreed. I can add this documentation later today or tomorrow.
> 
> The roadmap that I'd like to see for this repository moving forward is as
> follows:
> 
> [] merge pull request #2, #3, and #4 after I add some documentation about the
>    shared packages ;)
> [] merge pull request 3(expose statsd format and send functions) and 4(statsd
>    extended: dogstatsd support) that I did to my fork here:
>    https://github.com/arenadotio/ocaml-statsd-client/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed
> [] Add testing which I'm working on for my fork and I'll upstream it when the
>    above bullet points get merged.
>    * cleanup the directories to have lib and test directories
> 
> [] Add CircleCI support so our tests get ran on each pull request
> [] Clean up readme, documentation, etc.
> [] Publish new packages(lwt & async) along with deprecated package
> [] Pull request to deprecate statsd-client
> 
>    * clean up the global config
>    * clean up global logging to use lwt logging and async logging where appropriate
> 
> [] Publish updated packages
> 
> All of the above, I'm more than happy to do over the next week or two. I just
> want to be on the same page as you. Let me know what you think!

Sounds good. My only hesitation is only whether it is necessary to both expose
the format and send functions and integrate the dogstatsd support directly
(and not in a separate package). In principle, if dogstatsd support is
included (and I think it should, saving extra administrative work), it should
be possible to avoid exposing the interface of the internals it builds upon
(by not installing the cmis). However, the effort involved (extra modules,
aliases with shrunk signatures, jbuilder/dune stuff) looks excessive just to
hide a couple functions (send, send_with_ipaddr_and_port).

-- 
Mauricio Fernández

**Comment by bradlangel** [comment]
@mfp I've added a comment in the mli about the shared configuration behavior. Let's merge this! :)

**Comment by bradlangel** [comment]
Friendly reminder for review :)

**Comment by mfp** [comment]
I apologize for the delay. Just one Q before I merge: I just realized you're exposing `socket_ref`, `send_with_ipaddr_and_port`, `send` and `(>>=)` in `Statsd_client_core.T`, thus adding them to the original interface. Is this deliberate (I'm referring to the 3 first ones, `>>=` can surely be removed, right?), or can we comment them out? I mean, there's of course no problem if there is a reason for it, but if not, we can be conservative and promise (in terms of interface and its future compatibility) as little as possible :)

**Pull request closed without merging**
